# Generated by Django 5.1.3 on 2024-11-22 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('harga_per_hari', models.DecimalField(decimal_places=0, max_digits=10)),
                ('gambar', models.ImageField(upload_to='book/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=17)),
                ('nama_peminjam', models.CharField(max_length=250)),
                ('tanggal_pinjam', models.DateField(default=django.utils.timezone.now)),
                ('tanggal_kembali', models.DateField()),
                ('jumlah_bayar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sudah_bayar', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DIPESAN', 'Dipesan'), ('DIPINJAM', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan')], default='DIPESAN', max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='rental.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rental.platform'),
        ),
    ]
